name: Document Formatter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  yaml-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.24
        continue-on-error: true